# Generated by Django 4.2.6 on 2024-01-17 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('artwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('artwork_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(0, 'Not Rated'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0)),
                ('picture', models.ImageField(upload_to='home/picture/')),
                ('creation_time', models.TimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
