# Generated by Django 4.2.6 on 2024-01-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('exhibition_id', models.AutoField(primary_key=True, serialize=False)),
                ('exhibition_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=20)),
                ('exhibition_place', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='home/picture')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
    ]
