# Generated by Django 4.2.6 on 2024-01-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_exhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateField()),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exhibition')),
            ],
            options={
                'unique_together': {('exhibition', 'start_time', 'finish_time')},
            },
        ),
        migrations.CreateModel(
            name='Exhibition_Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exhibition')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exhibition', 'viewer')},
            },
        ),
        migrations.CreateModel(
            name='Artwork_Exhibition_Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.artwork')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exhibition')),
            ],
            options={
                'unique_together': {('exhibition', 'artwork', 'curator')},
            },
        ),
    ]
