# Generated by Django 4.2.6 on 2024-01-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanse_viewer',
            name='ticket',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
