# Generated by Django 4.2.6 on 2024-01-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sanse_viewer_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sans',
            name='start_time',
            field=models.DateField(),
        ),
    ]
